FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -B -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/CarniveroCrud-0.0.1-SNAPSHOT.jar app.jar
COPY uploads ./uploads
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
