spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carnivario?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: carnivario
    password: carnivario
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: false
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: 8081
jwt:
  secret: K7/yT1X0avLam999999999SedeCentral100LaPintanaadmincarniveroclGlobalAdmin2a10kGoXrQfppLBjS7hj6L8EuN0dT7NgWW
  expiration: 86400
